//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autores_has_libros
    {
        public int id { get; set; }
        public int autores_id { get; set; }
        public int libros_ISBN { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
