//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Autores_has_libros = new HashSet<Autores_has_libros>();
        }
    
        public int ISBN { get; set; }
        public int editoriales_id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string n_paginas { get; set; }
    
        public virtual Editoriales Editoriales { get; set; }
        public virtual ICollection<Autores_has_libros> Autores_has_libros { get; set; }
    }
}
